### PR TITLE
Fix typo in Keiko's name

### PR DESCRIPTION
**Pull request by rwz**

### CODE REVIEW

**Comment by keiko713** [comment]
EVEN THOUGH YOU DID INTENTIONALLY @brandur , I'm huge +1 for this PR.

**Comment by brandur** [comment]
Oh wow, what a **perfectly unintentional and honest mistake** on my part. There's absolutely no way that I'd misspell Kieko's name on purpose!

Okay, I guess this an improvement. +1. Thanks Pavel!

**Comment by keiko713** [comment]
You misspelled again, thanks Brandon.

**Comment by brandur** [comment]
Ye of little faith!

**Pull request merged**
